"""Checkpoint and metadata management."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any

import torch

from .constants import (
    LABEL_TRANSFORM,
    METADATA_SUFFIX,
    MODEL_VERSION,
    SCHEMA_VERSION,
    WAVENUMBER_MAX,
    WAVENUMBER_MIN,
    WAVENUMBER_STEP,
)
from .utils import now_utc_iso, read_json, write_json


class CheckpointMetadataError(RuntimeError):
    """Raised when checkpoint metadata is absent or incompatible."""


def metadata_path_for_checkpoint(checkpoint_path: str | Path) -> Path:
    """Return sidecar metadata path for a checkpoint."""
    ckpt = Path(checkpoint_path)
    return ckpt.with_name(f"{ckpt.stem}{METADATA_SUFFIX}")


def hash_target_species(target_species: list[str]) -> str:
    """Stable hash of target species ordering."""
    data = "|".join(target_species).encode("utf-8")
    return hashlib.sha1(data).hexdigest()


def build_checkpoint_metadata(
    target_species: list[str],
    *,
    model_version: str = MODEL_VERSION,
    train_data_manifest_hash: str | None = None,
    notes: str = "",
) -> dict[str, Any]:
    """Create standard checkpoint metadata payload."""
    return {
        "schema_version": SCHEMA_VERSION,
        "model_version": model_version,
        "target_species": list(target_species),
        "target_species_hash": hash_target_species(target_species),
        "grid_min": WAVENUMBER_MIN,
        "grid_max": WAVENUMBER_MAX,
        "grid_step": WAVENUMBER_STEP,
        "label_transform": LABEL_TRANSFORM,
        "train_data_manifest_hash": train_data_manifest_hash,
        "created_utc": now_utc_iso(),
        "notes": notes,
    }


def save_checkpoint(
    checkpoint_path: str | Path,
    state_dict: dict[str, torch.Tensor],
    metadata: dict[str, Any],
) -> None:
    """Persist model state dict and sidecar metadata."""
    ckpt = Path(checkpoint_path)
    ckpt.parent.mkdir(parents=True, exist_ok=True)
    torch.save(state_dict, ckpt)
    write_json(metadata_path_for_checkpoint(ckpt), metadata)


def load_metadata(checkpoint_path: str | Path, *, strict: bool = True) -> dict[str, Any] | None:
    """Load checkpoint metadata if present."""
    meta_path = metadata_path_for_checkpoint(checkpoint_path)
    if not meta_path.exists():
        if strict:
            raise CheckpointMetadataError(
                f"Missing checkpoint metadata sidecar: {meta_path}. "
                "Create metadata or use a checkpoint generated by the new pipeline."
            )
        return None
    return read_json(meta_path)


def validate_metadata(
    metadata: dict[str, Any],
    *,
    expected_target_species: list[str] | None = None,
) -> None:
    """Validate checkpoint metadata against runtime expectations."""
    required = {
        "model_version",
        "target_species",
        "grid_min",
        "grid_max",
        "grid_step",
        "label_transform",
        "label_normalizer",
    }
    missing = sorted(required - set(metadata.keys()))
    if missing:
        raise CheckpointMetadataError(f"Metadata missing required fields: {missing}")

    if metadata.get("label_transform") != LABEL_TRANSFORM:
        raise CheckpointMetadataError(
            f"Unsupported label transform: {metadata.get('label_transform')} (expected {LABEL_TRANSFORM})"
        )

    if float(metadata.get("grid_min")) != WAVENUMBER_MIN:
        raise CheckpointMetadataError("Checkpoint grid_min does not match runtime grid")
    if float(metadata.get("grid_max")) != WAVENUMBER_MAX:
        raise CheckpointMetadataError("Checkpoint grid_max does not match runtime grid")
    if float(metadata.get("grid_step")) != WAVENUMBER_STEP:
        raise CheckpointMetadataError("Checkpoint grid_step does not match runtime grid")

    if expected_target_species is not None:
        got = list(metadata.get("target_species", []))
        if got != list(expected_target_species):
            raise CheckpointMetadataError(
                f"Checkpoint target species mismatch. expected={expected_target_species}, got={got}"
            )


def load_state_dict_or_raise(model: torch.nn.Module, checkpoint_path: str | Path, map_location: torch.device) -> None:
    """Load checkpoint weights with explicit architecture compatibility error."""
    ckpt = Path(checkpoint_path)
    try:
        state = torch.load(ckpt, map_location=map_location, weights_only=False)
        if "model_state_dict" in state:
            state = state["model_state_dict"]
        model.load_state_dict(state)
    except RuntimeError as exc:
        raise CheckpointMetadataError(
            "Checkpoint is incompatible with current model architecture. "
            f"checkpoint={ckpt} error={exc}"
        ) from exc
